export const userResourceOptions = {
  listProperties: [
    'id',
    'firstName',
    'lastName',
    'role',
    'email',
    'password',
    'phone',
    'avatar',
    'fullName',
    'settings',
    'createdAt',
    'updatedAt',
  ],

  showProperties: [
    'firstName',
    'lastName',
    'role',
    'email',
    'phone',
    'avatar',
    'fullName',
    'settings',
    'createdAt',
    'updatedAt',
  ],

  editProperties: [
    'id',
    'firstName',
    'lastName',
    'role',
    'email',
    'password',
    'phone',
    'avatar',
    'fullName',
    'settings',
    'createdAt',
    'updatedAt',
  ],

  properties: { encrypted: { isVisible: false } },
};
